apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
        track: stable
    spec:
      containers:
        - name: nginx
          image: "nginx:1.9.14"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
      volumes:
        - name: "nginx-conf"
          configMap:
            name: "nginx-conf"
            items:
              - key: "default.conf"
                path: "default.conf"
