version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - 8000:8000
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
    networks:
      - my-network

  frontend:
    build: ./front-end-nextjs
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
    networks:
      - my-network

networks:
  my-network: