name: Build and Push to Artifact Registry

on:
  push:
    branches: [ "main" ]
    paths: ["**/VERSION"]

env:
  PROJECT_ID: sodium-hue-427709-u4
  GAR_LOCATION: us-central1
  GAR_REPO_NAME: qr-code-generator

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          access_token_lifetime: 300s
      - 
        name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
      -
        name: Build and Push Images
        run: |-
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "VERSION");
          do
            FOLDER=${versionFilePath%"/VERSION"}
            IMAGE_NAME=${FOLDER##*/}

            docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/$IMAGE_NAME:${{ github.sha }}" --file "$FOLDER/Dockerfile" $FOLDER
            docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/$IMAGE_NAME:${{ github.sha }}"
          done;